### PR TITLE
Add fluid math functions.

### PR DESCRIPTION
**Pull request by wanglei828**
Since math functions are elementary modules, I move the math folder out of operations folder and put it parallel with other main modules.

### CODE REVIEW

**Comment by wanglei828** [comment]
There two tests in math folder "math_function_test" and "sequence_padding_test" will depends on unimported code base. I temporally comment them out.

**Comment by wangkuiyi** [comment]
I feel that this PR might be too big that it is not very easy to identify the failure of CI. 

I see that the CI is complaining about cannot find CBLAS

```
[100%] Linking CXX executable selected_rows_functor_test
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/fluid/math/selected_rows_functor_test] Error 1
make[1]: *** [paddle/fluid/math/CMakeFiles/selected_rows_functor_test.dir/all] Error 2
```

**Comment by wanglei828** [comment]
@wangkuiyi Yes, last night I chat with Luotao about the cblas settings in paddle, and I will try to resolve this today.

**Comment by wanglei828** [comment]
@wangkuiyi Actually, before I sent this PR. I tested it in my local linux environment. It has passed all the tests. I think my machine has different setting with travis CI container.

**Pull request closed without merging**
